PR :: Feature/introduction pager activity publishing
team-nk/kim-il-jeong-android pull request #11
Opened 2023-01-07 07:34 UTC by Tmdhoon2

2023-01-07 08:44 UTC, JunJaBoy requested changes

2023-01-07 08:44 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionPagerActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
BaseActivity에 `initView()` 함수 추가해서 뷰 초기화 관리해 주세요!

2023-01-07 08:44 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionPagerActivity.kt
> +class IntroductionPagerActivity : BaseActivity<ActivityIntroductionPagerBinding>(
IntroductionActivity로 변경합시다

2023-01-07 08:44 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionPagerActivity.kt
> +class IntroductionPagerActivity : BaseActivity<ActivityIntroductionPagerBinding>(
Adapter랑 Layout도 마찬가지로

2023-01-07 10:19 UTC, JunJaBoy requested changes

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseActivity.kt
> +    abstract fun initView()
이렇게 해도 상관은 없는데 BaseActivity를 상속받는 뷰에서 `initView`를 구현하기 위해서는 해당 상속받는 View의 `onCreate`에서 `initView` 메서드를 호출해 주어야 합니다

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseActivity.kt
> +    abstract fun initView()
무조건 동작하는 보일러플레이트 코드가 한 줄 가미되는 것이죠

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseActivity.kt
> +    abstract fun initView()
그래서 BaseActivity의 `onCreate`에서 `initView`를 호출해 주면 baseActivity를 상속받는 클래스에서 `onCreate`에 따로 명시 없이 `initView` 함수를 적어서 사용할 수 있습니다

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseFragment.kt
> +    abstract fun initView()
이 친구도 마찬가지로 `onViewCreated`에서 `initView`를 호출해 주심 됩니다

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionActivity.kt
> +    override fun initView() {
위에 커멘트 이해 하시면 이 친구가 아무런 의미 없다는 것을 알게 될거에요

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionAdapter.kt
> +class IntroductionAdapter(private val context: Context) : PagerAdapter() {
프로퍼티 개행 하시고 트레일링 컴마 부탁드립니다

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/start/StartActivity.kt
> +    override fun initView() {
개인적인 습관인데 body를 구현하지 않는 함수는 한 줄에 모두 정리하는 편입니다
`override fun initView() {}` 이런 식으로?

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/start/StartActivity.kt
> +    override fun initView() {
전혀 상관 없는 이야기이고 고치지 않으셔도 돼요!!

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/res/layout/activity_introduction.xml
> +            android:id="@+id/tabLayout_introduction_viewPager"
아마 제가 리팩토링하면서 그랬을 수도 있는데 스네이크 케이스랑 카멜 케이스를 혼용하고 있네요

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/res/layout/activity_introduction.xml
> +            android:id="@+id/tabLayout_introduction_viewPager"
id Resource는 스네이크 케이스로 작성해야 합니다

2023-01-07 10:19 UTC, JunJaBoy commented on app/src/main/res/layout/activity_introduction.xml
> +            android:id="@+id/tabLayout_introduction_viewPager"
`tab_layout_introduction_vp` 이런 느낌으로

2023-01-07 10:21 UTC, Tmdhoon2 commented on app/src/main/java/app/junsu/kimiljeong/presentation/base/view/BaseActivity.kt
> +    abstract fun initView()
오

2023-01-08 02:22 UTC, JunJaBoy requested changes

2023-01-08 02:22 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionAdapter.kt
> +    private val context: Context,
제 고집이어서 들을 필요는 없지만 개인적으로 다른 클래스의 파라미터에 주는 컨텍스트는 `mContext`로 명명하는 편입니다

2023-01-08 02:22 UTC, JunJaBoy commented on app/src/main/java/app/junsu/kimiljeong/presentation/view/introduction/IntroductionAdapter.kt
> +    private val context: Context,
왜냐면 context는 코루틴에 있는 변수명이어서 중복 우려가 있어요

2023-01-08 02:22 UTC, JunJaBoy commented on app/src/main/res/layout/activity_introduction.xml
> +            android:id="@+id/tab_layout_introduction_viewPager"
카멜케이스 지워주시고 layout_introduction_view_pager로 바꿔주세요

2023-01-08 05:14 UTC, JunJaBoy approved these changes

2023-01-08 05:14 UTC, merged